In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import imblearn

In [3]:
df = pd.read_csv('Heart_Disease.csv')

In [4]:
df.head()

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
0,1,39,4.0,0,0.0,0.0,0,0,0,195.0,106.0,70.0,26.97,80.0,77.0,0
1,0,46,2.0,0,0.0,0.0,0,0,0,250.0,121.0,81.0,28.73,95.0,76.0,0
2,1,48,1.0,1,20.0,0.0,0,0,0,245.0,127.5,80.0,25.34,75.0,70.0,0
3,0,61,3.0,1,30.0,0.0,0,1,0,225.0,150.0,95.0,28.58,65.0,103.0,1
4,0,46,3.0,1,23.0,0.0,0,0,0,285.0,130.0,84.0,23.10,85.0,85.0,0

In [5]:
df.dropna(inplace=True)

In [6]:
df.isnull().sum()

male               0
age                0
education          0
currentSmoker      0
cigsPerDay         0
BPMeds             0
prevalentStroke    0
prevalentHyp       0
diabetes           0
totChol            0
sysBP              0
diaBP              0
BMI                0
heartRate          0
glucose            0
TenYearCHD         0
dtype: int64

In [7]:
X = df.drop('TenYearCHD',axis=1)
y = df['TenYearCHD']

In [55]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 54)

In [56]:
print("Before OverSampling, counts of label '1': {}".format(sum(y_train == 1))) 
print("Before OverSampling, counts of label '0': {} \n".format(sum(y_train == 0))) 
  
# import SMOTE module from imblearn library 
# pip install imblearn (if you don't have imblearn in your system) 
from imblearn.over_sampling import SMOTE 
sm = SMOTE(random_state = 2) 
X_train_res, y_train_res = sm.fit_sample(X_train, y_train.ravel()) 
  
print('After OverSampling, the shape of train_X: {}'.format(X_train_res.shape)) 
print('After OverSampling, the shape of train_y: {} \n'.format(y_train_res.shape)) 
  
print("After OverSampling, counts of label '1': {}".format(sum(y_train_res == 1))) 
print("After OverSampling, counts of label '0': {}".format(sum(y_train_res == 0)))

Before OverSampling, counts of label '1': 385
Before OverSampling, counts of label '0': 2175

After OverSampling, the shape of train_X: (4350, 15)
After OverSampling, the shape of train_y: (4350,)

After OverSampling, counts of label '1': 2175
After OverSampling, counts of label '0': 2175

In [57]:
from sklearn.tree import DecisionTreeClassifier
dt1 = DecisionTreeClassifier(random_state=54) 
dt1.fit(X_train_res, y_train_res.ravel()) 
predictions = dt1.predict(X_test) 

from sklearn.metrics import classification_report
# print classification report 
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       0.87      0.83      0.85       926
           1       0.27      0.34      0.30       172

    accuracy                           0.75      1098
   macro avg       0.57      0.58      0.57      1098
weighted avg       0.78      0.75      0.76      1098

In [58]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,predictions)

0.7513661202185792

In [59]:
from sklearn.metrics import f1_score
f1_score(y_test,predictions)

0.2982005141388175

In [60]:
X_test

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose
1263,0,49,1.0,0,0.0,0.0,0,0,0,270.0,126.5,67.5,26.56,70.0,77.0
4213,1,48,2.0,0,0.0,0.0,0,0,0,193.0,141.0,95.0,27.89,75.0,84.0
2145,1,62,2.0,0,0.0,0.0,0,0,0,202.0,149.5,85.0,25.42,65.0,80.0
1224,1,41,1.0,0,0.0,0.0,0,0,0,255.0,120.5,85.5,30.85,100.0,79.0
3667,1,49,1.0,1,20.0,0.0,0,0,0,155.0,128.0,82.0,23.58,69.0,77.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2225,1,38,4.0,0,0.0,0.0,0,0,0,240.0,122.5,80.0,23.97,60.0,43.0
3403,1,46,2.0,1,30.0,0.0,0,0,0,250.0,123.0,76.0,21.66,55.0,78.0
1278,1,53,1.0,1,30.0,0.0,0,0,0,253.0,121.0,85.5,28.52,80.0,68.0
1349,1,64,1.0,1,30.0,0.0,0,0,0,185.0,114.0,73.0,34.53,75.0,97.0
1683,0,39,1.0,0,0.0,0.0,0,0,0,164.0,112.0,63.0,22.01,60.0,85.0

In [54]:
new_predictions = dt1.predict([[1,58,3.0,0,0.0,0.0,0,1,0,187.0,141.0,81.0,24.96,80.0,81.0]])
new_predictions

array([0], dtype=int64)